### ISSUE TITLE
XRTOS view keeps turning on after restarting vscode

### ISSUE THREAD

**Issue by itzandroidtab** [mcu-debug/rtos-views#16]
After turning off XRTOS views in the command window it keeps turning itself back on after a restart of vscode:

https://youtu.be/jFtUWc5dhno

**Comment by haneefdm** [comment]
Already working on it...thanks for reporting.

**Comment by haneefdm** [comment]
A new release just made to fix the issue. There is a setting as well. As before you can also use VSCode's own mechanism to show/hide the view. We prefer using our setting. Using both methods can be confusing and can get out of sync.

Let us know if this fixes the problem

**Comment by itzandroidtab** [comment]
I just tested, it and it is working fine. Thank you
