### ISSUE TITLE
hint is not visible in xrtos window

### ISSUE THREAD

**Issue by venu942000** [mcu-debug/rtos-views#17]

**Comment by haneefdm** [comment]
Need test case. See screenshot in the following issue. There is zero probability that I can reproduce what you have.

https://github.com/mcu-debug/rtos-views/issues/15#issuecomment-1406663697

**Comment by haneefdm** [comment]
You also did not attach a full screenshot of the window. I saw a partial one, I want to see the full screenshot.

**Comment by xy-23** [comment]
Hi, I also met this problem. I've tried both on macOS Sonoma 14.5 and Windows on Arm 11
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/3ed72f52-1b11-44fe-b41d-d7f1e9f11488">

**Comment by xy-23** [comment]
It seems related to the thread id. As the following images shows, if the thread id disappears, so does the hint. However if the thread id behaves normal, then the hint can display.
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/c34a905d-b3a0-401e-86df-8a173d6fe07c">
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/8da6026c-fa12-4e92-879b-4b123f8f4696">

**Comment by haneefdm** [comment]
Hmmmm. Thanks for reporting this.
