### ISSUE TITLE
threadx supported?

### ISSUE THREAD

**Issue by frank-amy** [mcu-debug/rtos-views#19]
Hello,  do we have some plans about supporting Threadx

**Comment by haneefdm** [comment]
Not unless we can find a ThreadX expert to contribute. If you see our readme, most support is from contributors. I own the extension but I cannot be an expert at every RTOS :-)

Btw, MS Embedded tools supports RTOS views and we complement each other. Install their extension. They have support for cortex-debug. Not sure which debugger you are using

https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-embedded-tools

We may not have feature parity but we display some of the same info. Good luck

Please close this issue unless you want to contribute., It is a lot of work, I warn you.

**Comment by frank-amy** [comment]
thanks very much, I've tried MS embedded tool, bus it still has some something wrong to show the usage
