### ISSUE TITLE
OS Awareness plugin support

### ISSUE THREAD

**Issue by gparmeggiani** [mcu-debug/rtos-views#40]
To my knowledge, this extension supports only a predetermined set of RTOSs. 

I believe it would be very useful to add the capability to load an external plugin that uses some "OS awareness SDK" that adds support for any custom RTOS.

**Comment by haneefdm** [comment]
We don't call it a plugin but it is already structured that way. And, using that mechanism several contributors have added support for their favorite RTOS. Of course, you need to be an expert at your RTOS.  See

https://github.com/Marus/cortex-debug/issues/685
https://github.com/Marus/cortex-debug/issues/732

One of these days, we should create a page for this.

Please note that this extension is not for Call Stacks. That is already handled by the debugger(s). This is for viewing RTOS internals

Start your own and submit a PR like others have done.
