### ISSUE TITLE
Why there is some missing info?

### ISSUE THREAD

**Issue by J-Rios** [mcu-debug/rtos-views#47]
Hello,

Really nice plugin to work with RTOS projects, thanks a lot for this.

I started to use this plugin with FreeRTOS v8 and have the same missing information (stack sized, stack used, stack peak, etc) as you have shown in one of the images on the README file:

![imagen](https://github.com/mcu-debug/rtos-views/assets/12136967/6892f585-11e1-4234-86a9-4806d1015632)

I just want to ask, why is this information missing and if there is anything that I could do to configure the plugin or the project to get this info, or if it just a limitation depending on the type of RTOS and RTOS version used?

Best Regards.

**Comment by haneefdm** [comment]
Because those are compile time options. Did you click on hints link at the bottom of the image?

**Comment by PhilippHaefele** [comment]
Hi @J-Rios 

you need to click on `Hints to get more out of the FreeRTOS viewer` below the table to get information on how to get the missing values working.

**Comment by haneefdm** [comment]
@J-Rios Please close this if it worked for you

**Comment by J-Rios** [comment]
Oh, I did not realize that text was clickable, I will check...
